# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Gemas
gems:
  - jekyll-seo-tag

# Site settings
title: HorMinka
email: info@horminka.org
description: > # this means to ignore newlines until "baseurl:"
  Organización multidisciplinaria que busca a través de la ciencia y la tecnología contribuir al desarrollo de la sociedad, partiendo de la realidad local, regional y nacional.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.horminka.org" # the base hostname & protocol for your site
author: HorMinka
image: img/logo.jpg

twitter:
  username: horminka

facebook:
  publisher: https://www.facebook.com/horminka

logo: "img/logo.jpg"

social:
  name: Corporación HorMinka
  links: ["https://twitter.com/horminka", "https://www.facebook.com/horminka", "https://www.instagram.com/horminka/", "https://www.youtube.com/channel/UCOAlZBWlJajq7cs-89Ww3bA"]

disqus: horminka

# Build settings
markdown: kramdown

colores: [ "#ffbe4f", "#6bd2db", "#e8702a", "#0c457d", "#0ea7b5" ]
colores-clases: [ "amarillo", "azul", "azul-muy-claro", "naranja", "azul-claro", "azul-horminka", "naranja" ]

t:
  Español:
    navegacion: "Navegación"
    contratar: "Contratar con HorMinka es contribuir a la construcción de una sociedad mejor"
    trabajemos: "Trabajemos juntos por nuestra región"
    slogan: "Ciencia y Tecnología al Servicio de la Sociedad"
    ultimosposts: "Últimos posts"
    suscribete: "Suscríbete"
    textosuscribete: "Ingresa tus datos para suscribirte a nuestra lista de correo."
    enviar: "Enviar"
    vermas: "Ver más"
    queeshorminka: "¿Qué es HorMinka?"
    textoqueeshorminka: "Somos una organización sin ánimo de lucro de la ciudad de Neiva y buscamos a través de la ciencia y la tecnología contribuir al desarrollo de la sociedad. Por medio de consultorías, proyectos, investigación, formación y eventos acercamos las herramientas de la ciencia y la tecnología a personas, organizaciones y negocios, teniendo en cuenta la realidad local."
    nuestrosservicios: "Nuestros servicios"
    textonuestrosservicios: "HorMinka ofrece servicios orientados a la adopción de tecnologías que respeten la libre difusión del conocimiento, incentiven el entendimiento de su componente social, económico y ambiental, y a su vez que promuevan la visión crítica de su uso. La prestación de estos servicios aseguran la sostenibilidad de la organización. ¡Contratar con HorMinka es contribuir a la construcción de una sociedad mejor!"
    tituloserviciocursos: "Cursos"
    descripcionserviciocursos: "Ofrecemos formación en ciencia y tecnología a través de diferentes cursos presenciales de 20 horas"
    vercatalogocursos: "Ver catálogo de cursos"
    tituloserviciotalleres: "Talleres"
    descripcionserviciotalleres: "Compartimos conocimiento en ciencia y tecnología por medio de sesiones teórico-prácticas"
    vercatalogotalleres: "Ver catálogo de talleres"
    tituloservicioconfs: "Conferencias"
    descripcionservicioconfs: "Realizamos conferencias para exponer importantes temas de actualidad en ciencia y tecnología"
    vercatalogoconfs: "Ver catálogo de conferencias"
    tituloservicioconsultorias: "Consultorías"
    descripcionservicioconsultorias: "Brindamos consultorías personalizadas en ciencia y tecnología a personas, organizaciones y empresas"
    vermasconsultorias: "Ver más"
    conferencias: "Conferencias"
    talleres: "Talleres"
    consultorias: "Consultorías"
    cursos: "Cursos"
    tituloproyectos: "Proyectos"
    textoproyectos: "Estos son algunos de los proyectos en los que estamos trabajando. ¿Deseas colaborar? Escríbenos a <a href='mailto:info@horminka.org'>info@horminka.org</a> o haz tu <a href='/donaciones/'>donación</a> a HorMinka."
    alfabetizacion: "Alfabetización Tecnológica"
    textoalfabetizacion: "Ofrecemos talleres y conferencias gratuitas a la comunidad sobre temáticas de interés general."
    interespublico: "Interés Público"
    textointerespublico: "Trabajamos para defender el interés público en asuntos de ciencia y tecnología."
    investigacion: "Investigación"
    textoinvestigacion: "Ciencia y tecnología para producir conocimiento que responde a las necesidades de la región."
    paginas:
      - nombre: "Inicio"
        enlace: ""
      - nombre: "Nosotros"
        enlace: "nosotros/"
      - nombre: "Servicios"
        enlace: "servicios/"
      - nombre: "Blog"
        enlace: "blog/"
      - nombre: "Proyectos"
        enlace: "proyectos/"
      - nombre: "Contacto"
        enlace: "contacto/"
      - nombre: "Donar"
        enlace: "donaciones/"
  English:
    navegacion: "Navigation"
    contratar: "Hiring HorMinka contributes to build a better society"
    trabajemos: "Let's work together for a better world"
    slogan: "Science and Technology for the Benefit of Society"
    ultimosposts: "Last posts"
    suscribete: "Subscribe"
    textosuscribete: "Enter your data for adding you to our mail list."
    enviar: "Send"
    vermas: "View more"
    queeshorminka: "What is HorMinka?"
    textoqueeshorminka: "We are a non-profit organization from the city of Neiva and aided by science and technology, we contribute to social development. Considering the local context, we bring science and technology to the people, organizations and businesses, by the means of consultantcy services, research, education and public events."
    nuestrosservicios: "Our services"
    textonuestrosservicios: "HorMinka offers a series of services conceived to promote a better understanding of the social, economic and evironmental aspects of science and technology; the adoption of technologies that respect the free diffusion of knowledge, and the formation of critical thinking regarding their utilization. Offering these services ensure the self-sustainability of our organization. Hiring with HorMinka is a contribution for a better society!"
    tituloserviciocursos: "Courses"
    descripcionserviciocursos: "We offer training in different topics related to science and technology in 20 hour courses"
    vercatalogocursos: "See courses list"
    tituloserviciotalleres: "Workshops"
    descripcionserviciotalleres: "We share knowledge in science and technology in short theory + practice sessions"
    vercatalogotalleres: "See workshops list"
    tituloservicioconfs: "Conferences"
    descripcionservicioconfs: "We bring forth important topics to the people"
    vercatalogoconfs: "See conferences list"
    tituloservicioconsultorias: "Consulting"
    descripcionservicioconsultorias: "We provide technology solutions for people and organizations"
    vermasconsultorias: "See more"
    conferencias: "Talks"
    talleres: "Workshops"
    consultorias: "Consultancy"
    cursos: "Courses"
    tituloproyectos: "Projects"
    textoproyectos: "These are some of the projects on which we are currently working. Want to help us? Write us at <a href='mailto:info@horminka.org'>info@horminka.org</a> or make a <a href='/donations/'>donation</a> to HorMinka."
    alfabetizacion: "Technological Literacy"
    textoalfabetizacion: "We offer free workshops and conferences to the community about topics of public interest."
    interespublico: "Public Interest"
    textointerespublico: "We fight for the defense of public interest of issues realated to science and technology."
    investigacion: "Research"
    textoinvestigacion: "Science and technology for producing knowledge appropriate to the local needs."
    paginas:
      - nombre: "Home"
        enlace: "home.html"
      - nombre: "About Us"
        enlace: "about-us/"
      - nombre: "Services"
        enlace: "services/"
      - nombre: "Blog"
        enlace: "blog-en/"
      - nombre: "Projects"
        enlace: "projects/"
      - nombre: "Contact"
        enlace: "contact/"
      - nombre: "Donate"
        enlace: "donations/"
